version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            bundle install --path vendor/bundle
      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle
      - run:
          name: Run specs
          command: bundle exec rspec spec
      - store_test_results:
          path: ~/rspec

  deploy_prod:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless
      - run:
          name: Deploy
          command: sls deploy -s prod


workflows:
  version: 2
  main:
    jobs:
      - test
      - deploy_prod:
          requires:
            - test
          filters:
            branches:
              only: master

notify:
  webhooks:
    - url: https://amazonaws.com/prod/notify_slack